header:
    bold: True 
    fore_ground: "#ff8c27"

label:
    bold: True 
    fore_ground: "#5cdcc1"

worksheets:
    - "Overview"
    - "DatabasesAndSizes"
    - "AdvanceSettings"
    - "TraceFlagsAndTempDB" 
    - "Replication"
    - "BackupHistory"
    - "TopRunningSPs"
    - "Fileinfo"
    - "SQLAgents"
    - "MemorySnap"
